# serverless.yml
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

service: arter-typescript-serverless-starter
    
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:AWS_STAGE}
  region: ${env:AWS_REGION}

functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
