# serverless.yml
plugins:
  - serverless-offline

service: arter-typescript-serverless-starter
    
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
